gText_Birch_Welcome::
	.string "Hello? \p"
	.string "Is anyone there?\p"
	.string "To anyone seeing this, \n"
	.string "My name is LUNA, Goddess of Creation.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I'm sure you know what these are...\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is in grave danger...\p"
	.string "Team Nyx plans to destroy\n"
	.string "everything we hold dearly in order\l"
	.string "to satisfy their horrific ideals..\p"
	.string "Team Lux wishes to rule\n"
	.string "the world under an iron fist\l"
	.string "in the name of justice...\p"
	.string "Unfortunatelty I can't do anything\n"
	.string "but watch as my world\l"
	.string "crumbles under division...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Ah! You answered my plea!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Reveal thy name...$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "You're {PLAYER}{KUN} who's coming\n"
	.string "to this world.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}, thank you for\n"
	.string "answering my cry for help!\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Good luck out there!\p"
	.string "$"
